version: '3'
services:
  redis:
    image: redis/redis-stack-server:latest
    volumes:
      - ./redis.conf:/etc/redis/redis.conf
    hostname: redis
    container_name: redis
    environment:
      - REDIS_PORT=6379
      - "REDIS_ARGS=--requirepass ${REDIS_PSWD}"
    networks:
      elemental_net:
        aliases:
          - redis
networks:
  elemental_net:
    external: true
